d4lfteam/d4lf

src/main.py
src/utils/game_settings.py

Return error and ask to change to small in case its medium or large

check font size

---

config/game_1920x1080.ini
config/game_2560x1440.ini
config/game_3440x1440.ini
config/game_3840x2160.ini
src/ui/inventory_base.py

Forgot to put the roi for the flag in the ini files and hardcoded 1080p value. Refined the area a bit more.

fav flag fix

---

src/item/find_descr.py

Can happen that the stash tab icons match against "common" items.

fix stash item detection

---

config/profiles/uniques.yaml

- adding missing unique Ring of Ravenous to list

Update uniques.yaml profile

---

assets/lang/enUS/sigils.json

- Add new lunar event positive affix

Update sigils.json - Fix Lunar Event Positive affix

---

README.md
config/params.ini
src/config/loader.py
src/config/models.py
src/loot_filter.py

Instead of just specifying the amount, you can now specify the actual tabs.
This has been asked for many times in discord

Add possibility to select specific stash tabs

---

src/item/filter.py
test/item/filter/data/affixes.py
test/item/filter/data/filters.py

- Adjusted all value comparisons to now include the specified number
- For example, 4 and "larger" will include 4.
- Similarly, 4 and "smaller" will also include 4.

Fix value comparisons

---

config/params.ini
src/config/loader.py

- Added missing value loader for keep_aspects. It was always using the default

Fix keep_aspects

---

README.md
src/config/models.py
src/item/filter.py
test/item/filter/data/affixes.py
test/item/filter/data/filters.py

- Added minGreaterAffixCount to count group
- Added corresponding unit tests
- Changed readme accordingly

Add minGreaterAffixCount to count group

---

README.md
src/config/models.py

Fixes: https://github.com/aeon0/d4lf/pull/237

Fix bug in minGreaterAffixCount validation

---

src/gui/importer/d4builds.py
src/gui/importer/diablo_trade.py
src/gui/importer/maxroll.py
src/gui/importer/mobalytics.py
src/item/descr/text.py

- Fixed "to_core_skills" for maxroll importer
- Fixed rare diablo.trade importer errors
- Improved logging for diablo.trade importer so future errors are easier to reproduce

Importer fixes

---

.github/workflows/release.yml
requirements.txt
src/item/descr/find_affixes.py

- Needed since we no longer trigger on tag push
- Pin numpy to <2

Fix release name + tag

---

.github/workflows/release.yml
src/gui/importer/common.py

- Fix discord message for real? :)
- Use more general httpx exception

More small fixes

---

.gitignore
README.md
requirements.txt
src/__init__.py
src/gui/importer/common.py
src/gui/importer/d4builds.py
src/gui/importer/diablo_trade.py
tests/gui/importer/test_diablo_trade.py

Sadly, the fix will only work for chrome. There is no undetected browser for firefox/edge and diablo.trade activated highest cloudfare protection

Fix diablo.trade

---

src/__init__.py
src/item/descr/item_type.py
src/scripts/vision_mode.py

fixes https://github.com/aeon0/d4lf/issues/394

Add missing exc handling

---

src/__init__.py
src/gui/importer/maxroll.py

- Fix guide import index
- Remove implicit from ring filter

Maxroll improvements (ring, build index, ...)

---

src/gui/importer/maxroll.py
src/tools/data/custom_uniques_enUS.json

- Added support for barb and necro placeholder items in maxroll import
- Removed affixes from uniques in maxroll import because quality of maxroll data is too bad to use

- Added pitfighters_gull unique

---

src/gui/d4lfitem.py
src/gui/dialog.py
src/gui/profile_tab.py
src/gui/qt_gui.py

Co-authored-by: Hugo GIRARD <hugo.girard94@gmail.com>
(cherry picked from commit fa4ca593c2aebf88e045a913211b0471f2237c15)

Merging in a profile editor gui from @Shebour

---

src/__init__.py
src/item/data/item_type.py
src/item/descr/read_descr_tts.py
src/scripts/loot_filter_tts.py
src/scripts/vision_mode_tts.py
src/tts.py

- Slowed filtering down slightly to prevent skips
- Fixed handling of legendary shields
- Vision Mode will show "Unique" instead of a black box if the item matched because it was unique

- Added joystick support for TTS vision mode

---

src/__init__.py
src/config/models.py
src/gui/profile_tab.py
src/gui/qt_gui.py
src/scripts/handler.py

- Removed "Are you sure" message when closing GUI as it wasn't working properly
- Forced only TTS Full to be used

- Fix for gui where it wouldn't load if you had no profiles

---

README.md
src/main.py

Made automatic local prefs check warning more clear on how to disable the warning if everything is working fine.
